language: bash
services: docker

env:
  matrix:
    - GAURUN_VERSION=0.4.2
    - GAURUN_VERSION=0.4.1
  global:
    # DOCKER_HUB_USERNAME
    - secure: "J6tIJby+cOPjVhbA97PHZtaJLvfwzBUJCTNYQQBHld/4vlRsy0PbCTroriyyGHr9QTIDML3gVR9ht1Q7Qo0EBlvUXbEk6xVsNtaaWTEBTpqLrpecTrIS9hLGf9lXNRFmb+v5yMnrS7Nzqa0ndl8Rf/phTivq+1PLrVrJUDFvowKn2QHx7mx7LYXygQoQQ8SG587LZuzPkYXBj1KNxMxPzJsP0a/uVubHJgQruu4Oc4Km9k5GHvK/ToWB9Q/p2lyhZvnPtHcjnYCyrdfe5odoIok7C6S3pt44L0LINMCWvWzhz8cWuT1Xlc56V9iLibz+OoHWcTIc8m0FFwohyCP4c9li2T1X4HH9VysFlSMDZujqDs33Jy5xTSTcZzP2UrclslI2/IByuejw1tI4q3VmTnfpJqk31u4JfxGM9OdcFjhQgTciOu5pNL9bVcVaC2UDidO8zMmaAk0++/tg1QwN+tTwTl1+K0auI+QOcxKz4xXsI8Ks8cjtHkkvF+fAn/ildQDa0Vzj9sGHDaUf4DkMyIQyfH9OSiPs0vcRWpKTs36SYsdi7mgmdl+7zq/yogSBQdj0sEUiSIW1K3cw5N3+KPCCgVFHuiSGZa4wPtBe4hNa7z+IVhh0WZsaB5dPDiseTdddimglJ5WjS3q+UbE5ueQKslFKSr2YvS4FXIEyTfc="
    # DOCKER_HUB_EMAIL
    - secure: "C/+uI8FB0TLeyURTsoCW/vOQzH4Z+DRDTfu/AEtYj3nNWc/LmPVWNnh+ebZ8HH58D7rnH2dJ7igJslXeN03xk+j7MtmF29FcRBwZ0s1DFBDLIjAyLrNXGzqjAkOc/KjL1zOb+3yn1Dl73s6XHp3ZvG7Q+7nyJgWJqCPuDndJn4fuKX+r3ooZ0xJlBBSfz5g/0OHOZdsB1+Rt3GGCGvKXyNSbBwvs7MBmZhcag+FfTZ9n1wg34CJNF3Kserz1k/FNN9B+c9D8CkdsY7aZmJZ/5VdiMyK7mxHyvmOWpoDsPsChJK9bX0JWpjFjLIwMU+CEsKrc3CosC1arOMSR5257+bAmtpHFOFxA1nZFRWBMrm/cAqzSaxDtyXPQaXuOKOIwVLzV9NzD6BSy8ZoPCHnkbakCTOKMuocsZDKOjZTqrQSUSk07Dergu/CgIOv17wAw4DWtTKln7KU+OuIkttHueYfq0RPvbwJr3jh4a1Ipa6uvaTDgrwbWi+DfLLjXp2W5eUTzll7cWs/cRBu9TteZsDBDbPFsFidCB1ZI/sIduHKrP0+1/sNMlutikdLmRbTegbLku+CdU3h03PwvSoS5oSk+s7HWdBbbA7ZPVfg9AlB5huHl36scxtB5cPZi6q8yadtNw38ptSydKdsvBZkFmVCQRdsUoh1TuE9v50wcDc0="
    # DOCKER_HUB_PASSWORD
    - secure: "RQUjBmAGP5JJaPfadwwmAOH9qq5ONTFDdWpiBh+coD+iDfB+8+PDZbMzlq3sEcHbv3CCuHM2lGt1sgOcta03ZVv4TYpSzLCLEzTSyKgdr3oSI+MXxyWBdhVZ0O5RwFBfnTSi1OFavTDHrBuzyB9xOgDCBI0tFcXgue3aBDvlFQddV5B0Dz53y1g5XBwntz9/xyQckTdjwjLMlYuXMr5I9SeDTpR6SlergMc/LiIA02BpIhVa0a+yNHtYkD4LPHcyfVT3c43/DbCIFkRmSb9AWvGGlBvgn/cbk1xgL/VSBwN1muSG6LdP2UpiKN8qp7tO8Uvpd9Dnwx9j1mVTZBNyJssYEheJJN3E9S+HvgwqqmQl2n2mbgY7HY9j1/lkA5rplhXzCxyPTYiY63cwlG5s3tzgisEqHCKFhEAKO08ZRNEyjQRskkFPAFGkcbcdro6I+7qCvCGg+VveZwz+/gzzk3p2hydNPiMEZqNw0xF3mFBUfWclSocC30z9bCLb6yrLx4JqgXG3CsvhAJ8cmdN+BOflK68JjamglKoC5dMrnf2vTJx7VwGJbUHo7GCZHa5frakWhVvv4JgJWc850gvzHPCe9R9QgKKkOeSd68jjdSM0JMgy1vwQAc3UcIqN5IFuIk+ZO3EBj+ET09zuJMNnKfMM1Es1q03OCrcFn9Fw3H4="

before_script:
  - image="xcezx/gaurun:$GAURUN_VERSION"

script:
  - docker build -t "$image" .

after_script:
  - docker images

after_success:
  - docker login --username "$DOCKER_HUB_USERNAME" --email "$DOCKER_HUB_EMAIL" --password "$DOCKER_HUB_PASSWORD"
  - '[ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && docker push "$image"'
