language: bash
services: docker

env:
  matrix:
    - GAURUN_VERSION=0.4.2
    - GAURUN_VERSION=0.4.1
  global:

before_script:
  - image="xcezx/gaurun:$GAURUN_VERSION"

script:
  - docker build -t "$image" .

after_script:
  - docker images
  - docker login -e="$DOCKER_EMAIL" -u=$"DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_success:
  - '[ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ] && docker push "$image"'
